const lessons=[
['Samohlásky','Vowels','a, e, i/y, o, u → á, é, í/ý, ó, ú/ů','Šest základních písmen, pět krátkých zvuků. I a y znějí stejně; í a ý také. Čárka prodlužuje zvuk, nemění ho. Ú a ů mají stejný dlouhý zvuk. Ě není šestý samohláskový zvuk.','Six basic vowel letters, five short sounds. I and y sound alike, as do í and ý. An acute accent lengthens the sound. Ú and ů have the same long sound. Ě does not add a sixth vowel sound.'],
['Délka mění význam','Length changes meaning','byt × být · rada × ráda','Krátká a dlouhá samohláska jsou různé: byt je domov, být je sloveso. Dlouhý zvuk držte přibližně dvakrát déle. Délka není přízvuk.','Keep a long vowel roughly twice as long. Length can change a word’s meaning and is separate from stress. Czech vowels are pure: do not turn é or ó into English-style glides. English comparisons are only approximate.'],
['Tvrdé souhlásky','Hard consonants','h, ch, k, g, r, d, t, n','Tuto skupinu si zapamatujte. V běžných domácích slovech píšeme po tvrdých souhláskách zpravidla y/ý. D, t, n před i/í nebo ě obvykle změkčí výslovnost. Existují výjimky a přejatá slova: kino, historie.','Memorize this group. Hard consonants generally take y/ý in native Czech words. D, t, n usually soften before i/í or ě. This is not an absolute ban on i: borrowed words and exceptions exist.'],
['Měkké souhlásky','Soft consonants','ž, š, č, ř, c, j, ď, ť, ň','Pomůcka: souhlásky s háčkem plus c a j. Ď a ť mají háček napsaný jako malou čárku. V domácích slovech po měkkých souhláskách zpravidla píšeme i/í. Pro vzory podstatných jmen si tuto skupinu dobře zapamatujte.','Memory rule: consonants wearing a háček, plus c and j. The mark on ď and ť is a form of the háček. These consonants generally take i/í in native words. Remember this group for noun declension models.'],
['Obojetné souhlásky','Ambiguous consonants','b, f, l, m, p, s, v, z','Po těchto souhláskách může být i/í i y/ý. Volba závisí na slově nebo gramatice. Při výběru vzoru podstatného jména je spolu s tvrdými řadíme k tvrdým zakončením; další informace o slově jsou také důležité.','These can take either i/í or y/ý; the word or grammar determines the choice. For the beginner noun-model sorting used in our trainers, group them with hard endings. Gender and other features still matter.'],
['Písmeno ě: tři skupiny','The letter ě: three patterns','dě, tě, ně → ďe, ťe, ňe · bě, pě, vě, fě → bje, pje, vje, fje · mě → mňe','Ě je samohláskové písmeno. Píšeme ho jen po d, t, n, b, p, v, f, m. Dě/tě/ně změkčí souhlásku; bě/pě/vě/fě přidají j; mě vyslovujeme jako mňe. Fě je vzácné: o žirafě.','Ě is a vowel letter, written only after d, t, n, b, p, v, f, m. It softens d/t/n, signals a j sound after b/p/v/f, and mě sounds like mňe. Fě is rare: o žirafě (about a giraffe). It does not always sound like “ye”.'],
['Di, ti, ni a dy, ty, ny','Soft and hard d, t, n','di/dí → ďi/ďí · ti/tí → ťi/ťí · ni/ní → ňi/ňí','V běžných domácích slovech je di/ti/ni měkké; dy/ty/ny je tvrdé. Porovnejte: dík – dýka, hodní – hodný. U přejatých slov může být výslovnost tvrdá: diktát, titul.','In native words, di/ti/ni are usually soft, while dy/ty/ny are hard. Compare dík (thanks) and dýka (dagger). Borrowed words can keep hard pronunciation, as in diktát and titul.'],
['Důležité zvuky','Useful sounds','c = ts · č = ch · š = sh · ž = s in pleasure · j = y in yes','Ch je jedno písmeno a stojí po h. Zní jako ve skotském loch. G zní jako v anglickém goat. R je kmitavé, jako španělské r. Ř spojí kmitání se šumem: poslouchejte a zkoušejte pomalu. Q, w, x jsou hlavně v přejatých slovech.','CH is one letter, placed after H; its sound resembles Scottish loch. G is like goat. R is rolled, like Spanish r. Ř combines a tongue vibration with friction: listen and practise gradually. Q, w and x occur mainly in borrowed words.'],
['Přízvuk a dvojhlásky','Stress and diphthongs','první slabika · ou, au, eu','Přízvuk je obvykle na první slabice. Jednoslabičná předložka ho zpravidla přebírá: do školy, na poště. Dlouhá samohláska zůstává dlouhá i bez přízvuku. Ou je běžné; au a eu jsou častější v přejatých slovech. Ve slově používá jsou o a u oddělené.','Stress is normally on the first syllable, usually shifting to a preceding one-syllable preposition. An unstressed long vowel stays long. Ou is common; au and eu appear especially in loans. In používá, o and u belong to separate syllables.'],
['Na konci slova','At the end of a word','zub → zup · had → hat · muž → muš','Na konci slova před pauzou mohou znělé souhlásky znít nezněle. Pravopis se nemění. Poslouchejte také obchod, tužka a na shledanou; sousední souhlásky mohou ovlivnit výslovnost.','Before a pause, voiced consonants at word endings become voiceless. Spelling stays the same. Neighbouring consonants can also influence each other. Listen to obchod, tužka and na shledanou.'],
['Jak vybíráme vzor','How we choose a noun model','rod → samohláska / souhláska → měkká / tvrdá','Nejdřív určete rod. Potom se podívejte, jestli slovo končí samohláskou, nebo souhláskou. U slov zakončených souhláskou rozlište měkké a tvrdé zakončení. Mužská i ženská podstatná jména zakončená souhláskou mají různé vzory: pán má tvrdé zakončení, muž měkké; kost má tvrdé zakončení, báseň měkké. Pro tuto začátečnickou pomůcku počítáme obojetné souhlásky k tvrdým zakončením.','First identify the gender. Then check whether the word ends in a vowel or a consonant. For consonant endings, distinguish soft from hard. Masculine and feminine nouns ending in consonants have different patterns: pán has a hard ending, muž a soft ending; kost has a hard ending, báseň a soft ending. In this beginner sorting rule, ambiguous consonants count with hard endings.']
];
const groups=[
['a / á','Praha|Prague;mapa|map;máma|mum;malá|small (feminine);káva|coffee;kavárna|café;ráda|glad (feminine);zábava|fun'],
['e / é','den|day;metr|metre;jeden|one;lépe|better;mléko|milk;problém|problem;nechceme|we do not want;vede|leads'],
['i, y / í, ý','ryby|fish (plural);chyby|mistakes;vidličky|forks;bílý|white;milý|kind;mír|peace;syn|son;žijí|they live'],
['o / ó','pokoj|room;dopis|letter;poledne|noon;rok|year;horko|heat;gól|goal;haló|hello (on phone);program|programme'],
['u / ú, ů','ruku|hand (accusative);kus|piece;hůl|walking stick;kůl|stake;půjdu|I will go;domů|home (direction);úterý|Tuesday;stůl|table'],
['ě','běží|runs;oběd|lunch;pět|five;pěšky|on foot;svět|world;město|town;náměstí|square;děkuju|thank you;něco|something;těší mě|nice to meet you;o žirafě|about a giraffe'],
['di, ti, ni / dy, ty, ny','dítě|child;divadlo|theatre;lidi|people;mladý|young;tady|here;čistý|clean;hodní|kind (masculine plural);hodný|kind (masculine singular);hodiny|clock;není|is not'],
['ou, au, eu','houska|bread roll;louka|meadow;smlouva|contract;mouka|flour;poslouchá|listens;auto|car;autobus|bus;euro|euro;používá|uses'],
['ř / r','třída|classroom;dveře|door;moře|sea;dobře|well;talíř|plate;příbor|cutlery;středa|Wednesday;tři|three;ráno|morning'],
['č, š, ž, c, j','černý|black;červený|red;ručník|towel;večer|evening;čaj|tea;člověk|person;škola|school;šest|six;židle|chair;žena|woman;žlutý|yellow;citron|lemon;jídlo|food'],
['h / ch','ahoj|hello;hodina|hour;nahoře|upstairs;chléb|bread;chodí|walks;chyba|mistake;hlad|hunger;chlad|cold;hezký|nice'],
['Konec slova / word endings','zub|tooth;had|snake;muž|man;nůž|knife;obchod|shop;obraz|picture;tužka|pencil;teď|now;odpověď|answer']
];
const words=groups.flatMap(([g,s])=>s.split(';').map(x=>{const[t,en]=x.split('|');return{t,en,g}}));
const phrases=[['Máma má kávu.','Mum has coffee.','a / á'],['To je malá kavárna.','That is a small café.','a / á'],['Dáme si mléko.','We will have some milk.','e / é'],['Ryby jsou bílé.','The fish are white.','i, y / í, ý'],['To je můj pokoj.','That is my room.','o / ó'],['V úterý půjdu domů.','On Tuesday I will go home.','u / ú, ů'],['Děkuju za oběd.','Thank you for lunch.','ě'],['Jdu pěšky do města.','I am walking to town.','ě'],['Těší mě.','Nice to meet you.','ě'],['Dítě je v divadle.','The child is at the theatre.','di, ti, ni / dy, ty, ny'],['Tady jsou hodní lidi.','There are kind people here.','di, ti, ni / dy, ty, ny'],['Poslouchám v autobuse.','I am listening on the bus.','ou, au, eu'],['Používám telefon.','I use a phone.','ou, au, eu'],['Ve středu máme češtinu.','We have Czech on Wednesday.','ř / r'],['Na stole jsou tři talíře.','There are three plates on the table.','ř / r'],['Chci černý čaj.','I want black tea.','č, š, ž, c, j'],['Žlutá židle je ve škole.','The yellow chair is at school.','č, š, ž, c, j'],['Ahoj, jak se máš?','Hi, how are you?','h / ch'],['Chci chleba.','I want bread.','h / ch'],['Obchod je teď zavřený.','The shop is closed now.','Konec slova / word endings'],['Na poště.','At the post office.','Předložky / prepositions'],['Ve škole.','At school.','Předložky / prepositions'],['V Praze.','In Prague.','Předložky / prepositions'],['Jsem u lékaře.','I am at the doctor’s.','Předložky / prepositions'],['Jdu do školy.','I am going to school.','Předložky / prepositions']].map(([t,en,g])=>({t,en,g}));
const alphabet='a á b c č d ď e é ě f g h ch i í j k l m n ň o ó p q r ř s š t ť u ú ů v w x y ý z ž'.split(' ');
const names='á dlouhé-á bé cé čé dé ďé é dlouhé-é é-s-háčkem ef gé há chá í dlouhé-í jé ká el em en eň ó dlouhé-ó pé kvé er eř es eš té ťé ú dlouhé-ú ú-s-kroužkem vé dvojité-vé iks ypsilon dlouhé-ypsilon zet žet'.split(' ').map(s=>s.replaceAll('-',' '));
const quiz=[
['Která skupina obsahuje všechny měkké souhlásky?','Which group contains all soft consonants?',['ž š č ř c j ď ť ň','h ch k g r d t n','b f l m p s v z'],0,3],
['Která skupina obsahuje tvrdé souhlásky?','Which group contains the hard consonants?',['b f l m p s v z','h ch k g r d t n','ž š č ř c j ď ť ň'],1,2],
['Která skupina obsahuje obojetné souhlásky?','Which group contains ambiguous consonants?',['h ch k g r d t n','c j ř č','b f l m p s v z'],2,4],
['Po kterých písmenech můžeme napsat ě?','Which letters can precede ě?',['d t n b p v f m','h ch k g r','ž š č ř c j'],0,5],
['Jak se vyslovuje mě?','How is mě pronounced?',['me','mje','mňe'],2,5],
['Jak se vyslovuje dě?','How is dě pronounced?',['ďe','dje','de'],0,5],
['Jak se vyslovuje bě?','How is bě pronounced?',['be','bje','bňe'],1,5],
['Co znamená čárka nad samohláskou?','What does an acute accent mean?',['Silnější přízvuk / stronger stress','Delší zvuk / longer sound','Jiná souhláska / different consonant'],1,1],
['Která dvojice má stejný samohláskový zvuk?','Which pair has the same vowel sound?',['a – e','i – y','o – u'],1,0],
['Jaký je rozdíl mezi ú a ů ve výslovnosti?','How do ú and ů differ in pronunciation?',['Ú je krátké / ú is short','Ů má přízvuk / ů is stressed','Žádný / no difference'],2,0],
['Které písmeno vyslovujeme jako ts?','Which letter sounds like ts?',['c','č','j'],0,7],
['Které písmeno stojí v abecedě po h?','Which letter follows h in the alphabet?',['i','ch','g'],1,7],
['Kde je obvykle český přízvuk?','Where is Czech stress normally placed?',['Na poslední slabice / last syllable','Na dlouhé samohlásce / long vowel','Na první slabice / first syllable'],2,8],
['Je ě souhláska?','Is ě a consonant?',['Ano / yes','Ne, je to samohláskové písmeno / no, a vowel letter'],1,5],
['Která souhláska je měkká i bez háčku?','Which consonant is soft without a háček?',['r','j','k'],1,3],
['Jak vyslovíme zub před pauzou?','How is zub pronounced before a pause?',['zup','sub','zub s dlouhým u / with long u'],0,9],
['Jsou di a dy v domácích slovech stejné?','Do di and dy sound the same in native words?',['Ano / yes','Ne: di je měkké, dy tvrdé / no: di is soft, dy hard'],1,6],
['Je i po tvrdé souhlásce vždy nemožné?','Is i after a hard consonant always impossible?',['Ano / yes','Ne: např. kino / no: for example kino'],1,2],
['Co je důležité pro volbu vzoru podstatného jména?','What matters for choosing a noun model?',['Jen přízvuk / only stress','Rod a jestli slovo končí samohláskou, měkkou nebo tvrdou souhláskou / gender and whether the word ends in a vowel, a soft consonant or a hard consonant'],1,10],
['Která pomůcka označuje měkké souhlásky?','Which memory rule identifies soft consonants?',['Háček plus c a j / háček plus c and j','Čárka plus h / acute accent plus h','Všechny kromě r / all except r'],0,3]
];
